#[params]
#    description = "We offer you complex and professional oral and written Chinese-Polish–English translations covering business, technical and medical fields. All the translations are checked by native speakers."
#    mainIcon = "/img/at-logo.png"

# Site settings
baseurl = "http://aleksandratranslations.com/"
languageCode = "en-us"
title = "Aleksandra Translations"
theme = "hugo-agency-theme"
canonifyurls = true
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Your name"
    description = "We offer you complex and professional oral and written Chinese-Polish–English translations covering business, technical and medical fields. All the translations are checked by native speakers."

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "liaokarolina@me.com"


	# Navigation
	[params.navigation]
		brand = "Aleksandra Translations"
		services = "Services"
		portfolio = "About"
		about = "About"
		team = "Team"
		contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10

    # postpended links
    [[menu.postpend]]
        #url = "http://gohugo.io"
        #name = "External link"
        #weight = 10


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Aleksandra Translations"
		subtitle = "Your professional translator in English, Chinese, Polish"
		#buttonText = "Tell me more"


	# Services section
	[params.services]
        enable = true
		title = "Services"
		subtitle = "We offer you complex and professional oral and written Chinese-Polish–English translations covering business, technical and medical fields. All the translations are checked by native speakers."

        [[params.services.row]]

            [[params.services.row.list]]
                title = "Assistance in Business trips"

            [[params.services.row.list]]
                title = "Outsourcing new products in Chinese market"

            [[params.services.row.list]]
                title = "Translations during Canton Fair and HK Expo"

            [[params.services.row.list]]
                title = "Translations during Economic Conferences"

            [[params.services.row.list]]
                title = "Tour guides"

            [[params.services.row.list]]
                title = "Assistance in booking trips, hotels, cars"

	# Portfolio section
	[params.portfolio]
        enable = true
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "About"
		subtitle = "We will assist you in business negotiations, developing your business in China, during business negotiations or any time you simply need to reply the mail in Chinese. If you want to expand your business, enter Chinese market or find new suppliers in China, contact us."
        desc = "Liao and Damek offer you super professional translations within the cultural context, which make your business negotiations successful."

		[params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close project"

	# Team section
	[params.team]
        enable = true
		title = "Our amazing team"
		subtitle = "Liao and Damek offer you super professional translations within the cultural context, which make your business negotiations successful."

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "2.jpg"
			name = "Marcin Damek"
			position = "MA student in Chinese and Literature Studies at University of Warsaw, president of the Sinological Reseach Circle of University of Warsaw, Chinese Government Scholarship recipient. During academic year 2014/2015 he took part in an advanced Chine language course at Nanjing Normal University. He organized many academic (conferences), cultural (Chinese Culture Day) and language events (Shalong – interesting conversations with the Chinese). At his 1st year during BA studies he worked as a translator at China Expo Poland international fair in Warsaw. Since then he is involved in translation activities (both written and oral ones). In his free time he expands his interests in Chinese philosophy as well as enjoys swimming and mountain hiking"
			email = "marcindamek1991@gmail.com"
			phone = "＋48 696-422-009"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

		[[params.team.members]]
			img = "1.jpg"
			name = "Karolina Pakula"
			position = "Sinologist, Chinese Translator and Chinese culture lover. She has been studying Chinese language and culture at University of Warsaw and then felt in love with Chinese language, so she moved to Canton and started intensive Chinese language training at Zhongshan University (中山大学), where she has been studying for several years. Karolina reached the most advanced Mandarin level as well as passed Hanyu Shuiping Kaoshi (advanced level). Since then she is living in China and working as a translator, helping Polish businessman in entering Chinese market. Karolina has vast experience in business negotiations and translations during Canton Fair and Hong Kong Expo."
			email = "liaokarolina@me.com"
			phone = "+86 132-6839-6976"
			social = [
				["fa-twitter", "https://twitter.com/karolinapakula"],
				["fa-facebook", "#"],
				["fa-linkedin", "https://www.linkedin.com/in/karolina-pakula-9a002896"]
			]

	# Client section
    [params.clients_list]
        enable = true

    	# All the clients' logos are stored under 'static/img/logos'.
    	# Replace them with your clients's logos.
    	[[params.clients]]
    		logo = "envato.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "designmodo.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "themeforest.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "creative-market.jpg"
    		link = "#"


	# Contact section
	[params.contact]
        enable = true
		title = "Contact us"
		subtitle  = "We are happy to hear from you"
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
        enable = false
		copyright = "© 2016 Aleksandra Translations"

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "#"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "#"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "#"

		#[[params.footer.quicklinks]]
		#	text = "Privacy Policy"
		#	link = "#"

		#[[params.footer.quicklinks]]
		#	text = "Terms of Use"
		#	link = "#"
